// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydwcnouatgbpjlieyvlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkd2Nub3VhdGdicGpsaWV5dmxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzYyODEsImV4cCI6MjA3MTkxMjI4MX0.5wfDysy1Pyn8opEs5PvGBhnLmEcHkAlYJUBJBtMGh-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});